name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: basic metrics
              uses: lowlighter/metrics@main
              with:
                  filename: .cache/metrics.classic.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: header, activity, community, repositories
                  base_indepth: yes
                  base_hireable: yes

            - name: Compact display
              uses: lowlighter/metrics@main
              with:
                  filename: cache/metrics.plugin.achievements.compact.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: ""
                  plugin_achievements: yes
                  plugin_achievements_display: compact
                  plugin_achievements_threshold: X
