name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: basic metrics
              uses: lowlighter/metrics@main
              with:
                  filename: .renders/metrics.basic.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: header, activity, community, repositories
                  base_indepth: yes
                  base_hireable: yes

            - name: Compact display
              uses: lowlighter/metrics@main
              with:
                  filename: .renders/metrics.achievements.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: ""
                  plugin_achievements: yes
                  plugin_achievements_display: compact
                  plugin_achievements_threshold: X

            - name: Full-year calendar
              uses: lowlighter/metrics@main
              with:
                  filename: .renders/metrics.isocalendar.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: ""
                  plugin_isocalendar: yes
                  plugin_isocalendar_duration: full-year

            - name: Languages indepth
              uses: lowlighter/metrics@main
              with:
                  filename: .renders/metrics.languages.svg
                  token: ${{ secrets.METRICS_TOKEN }}
                  base: ""
                  plugin_languages: yes
                  plugin_languages_ignored: >-
                      html, css, less, dockerfile, makefile, qmake, lex, cmake,
                      gnuplot
                  plugin_languages_indepth: yes
                  plugin_languages_details: lines, bytes-size
                  plugin_languages_limit: 30
                  plugin_languages_analysis_timeout: 15
