name: Metrics
on:
    # Schedule daily updates
    schedule: [{ cron: "0 0 * * *" }]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: { branches: ["master", "main"] }

jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
            with:
                base: ".cache"
                filename: metrics.classic.svg
                token: ${{ secrets.METRICS_TOKEN }}
                base_indepth: yes
                plugin_lines: yes

            # - uses: lowlighter/metrics@main
            # with:
            #     plugin_languages: yes
            #     plugin_languages_indepth: yes
            #     token: ${{ secrets.METRICS_TOKEN }}
            # - uses: lowlighter/metrics@main
            # with:
            #     filename: metrics.plugin.achievements.compact.svg
            #     token: ${{ secrets.METRICS_TOKEN }}
            #     base: ".cache"
            #     plugin_achievements: yes
            #     plugin_achievements_display: compact
            #     plugin_achievements_threshold: X
